"""Small, dependency-free localization layer for the desktop interface."""

from __future__ import annotations

import locale


LANGUAGE_LABELS = {
    "en": "English",
    "ru": "Русский",
}


RUSSIAN_TRANSLATIONS = {
    "Smart recovery, distributed rendering, prediction and phone control.": "Умное восстановление, сетевой рендер, прогнозирование и управление с телефона.",
    "Smart queue": "Умная очередь",
    "Network ×5": "Сеть ×5",
    "Mobile control": "Мобильное управление",
    "History + Auto Fix": "История + автоисправление",
    "CURRENT STATE": "ТЕКУЩЕЕ СОСТОЯНИЕ",
    "Render": "Рендер",
    "Queue": "Очередь",
    "Network": "Сеть",
    "Insights": "Аналитика",
    "Sandbox": "Песочница",
    "Advanced": "Расширенные",
    "Settings": "Настройки",
    "Logs": "Журнал",
    "Project Setup": "Настройка проекта",
    "Scene file, output frames folder, and detected Blender runtime.": "Файл сцены, папка кадров и найденная версия Blender.",
    "Blender": "Blender",
    ".blend file": "Файл .blend",
    "Frames folder": "Папка кадров",
    "Browse": "Обзор",
    "Use .blend output path": "Использовать путь из .blend",
    "Render Device": "Устройство рендера",
    "Pick render devices. Cycles preferences are applied at launch.": "Выберите устройства. Настройки Cycles применяются при запуске.",
    "Use GPU": "Использовать GPU",
    "Use CPU": "Использовать CPU",
    "Render Timeline": "Ход рендера",
    "Start render": "Начать рендер",
    "Pause after frame": "Пауза после кадра",
    "Stop now": "Остановить",
    "Pause waits for the current frame, Stop terminates Blender now.": "Пауза дождётся текущего кадра, остановка завершит Blender сразу.",
    "Live Console": "Консоль",
    "Terminal stream, crashes, restarts and completed frames": "Вывод Blender, сбои, перезапуски и готовые кадры",
    "Render Queue": "Очередь рендера",
    "Estimate projects, put shorter work first, retry failures and continue automatically.": "Оценивает проекты, ставит короткие первыми, повторяет сбои и продолжает автоматически.",
    "Add current": "Добавить текущий",
    "Add files": "Добавить файлы",
    "Remove": "Удалить",
    "Estimate + sort": "Оценить и упорядочить",
    "Project": "Проект",
    "Frames": "Кадры",
    "Mode": "Режим",
    "Estimate": "Оценка",
    "Output": "Результат",
    "Status": "Статус",
    "Shortest projects first": "Сначала короткие проекты",
    "Start queue": "Запустить очередь",
    "Controller": "Контроллер",
    "Choose this device's role": "Выберите роль этого устройства",
    "Connect to another computer or make this computer the main render controller.": "Подключитесь к другому компьютеру или сделайте этот компьютер главным для рендера.",
    "Connect": "Подключиться",
    "Become main": "Стать главным",
    "Connect instead": "Перейти к подключению",
    "Connection type": "Тип подключения",
    "Local network (LAN)": "Локальная сеть (LAN)",
    "SSH tunnel": "SSH-туннель",
    "Install OpenSSH": "Установить OpenSSH",
    "Refresh": "Обновить",
    "OpenSSH: checking…": "OpenSSH: проверка…",
    "OpenSSH client and server are ready": "Клиент и сервер OpenSSH готовы",
    "OpenSSH server is installed but stopped": "Сервер OpenSSH установлен, но остановлен",
    "OpenSSH client is ready": "Клиент OpenSSH готов",
    "OpenSSH is not installed": "OpenSSH не установлен",
    "OpenSSH installer started with administrator rights": "Установка OpenSSH запущена с правами администратора",
    "OpenSSH installation": "Установка OpenSSH",
    "The SSH client is missing. Install it automatically and then press Connect again?": "SSH-клиент не установлен. Установить его автоматически, а затем снова нажать «Подключиться»?",
    "Install the Windows OpenSSH client and server?": "Установить клиент и сервер Windows OpenSSH?",
    "Install the Windows OpenSSH client?": "Установить клиент Windows OpenSSH?",
    "SSH address": "SSH-адрес",
    "SSH user": "Пользователь SSH",
    "SSH private key": "Приватный ключ SSH",
    "Choose SSH private key": "Выберите приватный ключ SSH",
    "SSH tunnel connected": "SSH-туннель подключён",
    "Connecting SSH tunnel…": "Подключение SSH-туннеля…",
    "Main computer": "Главный компьютер",
    "Connect to main computer": "Подключиться к главному компьютеру",
    "Use this computer for rendering": "Использовать этот компьютер для рендера",
    "Main": "Главный",
    "Online": "В сети",
    "Offline": "Не в сети",
    "Auto": "Авто",
    "Connected to {controller} · {online} devices": "Подключено к {controller} · устройств в сети: {online}",
    "Main PC name": "Имя главного ПК",
    "Stop controller": "Остановить контроллер",
    "Continue missing frames": "Продолжить недостающие кадры",
    "Manual frame range": "Ручной диапазон кадров",
    "Stop render": "Остановить рендер",
    "Automatic frames": "Автоматические кадры",
    "Empty Samples uses the scene setting": "Пустое поле Samples использует настройку сцены",
    "Manual frame range selected": "Выбран ручной диапазон кадров",
    "Continue: skip frames already in the output folder": "Продолжение: готовые кадры в папке вывода будут пропущены",
    "No network render is running": "Сетевой рендер не запущен",
    "Network render stopped; active frames may finish": "Сетевой рендер остановлен; активные кадры могут завершиться",
    "No new network frames will be assigned": "Новые сетевые кадры больше не назначаются",
    "Enter both Start frame and End frame for manual network rendering.": "Для ручного сетевого рендера укажите начальный и конечный кадры.",
    "This device is not available for render settings.": "Для этого устройства настройки рендера недоступны.",
    "Device render settings applied": "Настройки рендера устройства применены",
    "Scene": "Сцена",
    "Frames {start}-{end} · {skipped} existing skipped": "Кадры {start}-{end} · готовых пропущено: {skipped}",
    "Integrity check requeued frames: {frames}": "Проверка целостности вернула кадры в очередь: {frames}",
    "{completed} complete · {failed} failed · integrity verified": "Готово: {completed} · ошибок: {failed} · целостность проверена",
    "Create a LAN code and distribute individual frames to up to five PCs.": "Создайте код локальной сети и распределяйте кадры между пятью ПК.",
    "Visible main PCs can be selected on the LAN. New devices pair once and reconnect automatically.": "Видимый главный ПК можно выбрать в локальной сети. Новое устройство подключается один раз и затем переподключается автоматически.",
    "Start controller": "Запустить контроллер",
    "Copy code": "Копировать код",
    "Stop": "Остановить",
    "Start distributed render": "Запустить сетевой рендер",
    "Worker mode": "Режим исполнителя",
    "Enter the code on another computer. The project is downloaded automatically.": "Введите код на другом компьютере. Проект загрузится автоматически.",
    "This PC name": "Имя этого ПК",
    "Connection code": "Код подключения",
    "Advanced connection code": "Расширенный код подключения",
    "Show this main PC on the local network": "Показывать этот главный ПК в локальной сети",
    "Require a one-time code for new devices": "Запрашивать одноразовый код для новых устройств",
    "One-time code: {code}": "Одноразовый код: {code}",
    "One-time code": "Одноразовый код",
    "New code": "Новый код",
    "Not required": "Не требуется",
    "Select a visible main PC. A saved trusted connection reconnects without asking for a code again.": "Выберите видимый главный ПК. Сохранённое доверенное подключение больше не запрашивает код.",
    "Main PCs on local network": "Главные ПК в локальной сети",
    "One-time code (only for the first connection)": "Одноразовый код (только при первом подключении)",
    "Connect selected PC": "Подключиться к выбранному ПК",
    "Saved or SSH connection code": "Сохранённый код или код SSH-подключения",
    "Code required": "Нужен код",
    "Local network": "Локальная сеть",
    "No main PC was found. Refresh the list or use an advanced connection code.": "Главный ПК не найден. Обновите список или используйте расширенный код подключения.",
    "Enter the one-time code shown on the main PC.": "Введите одноразовый код, показанный на главном ПК.",
    "Install and start OpenSSH Server on the main PC first.": "Сначала установите и запустите OpenSSH Server на главном ПК.",
    "Enter a valid SSH address, port, and user.": "Введите корректные SSH-адрес, порт и имя пользователя.",
    "Install the OpenSSH client on this PC first.": "Сначала установите клиент OpenSSH на этом ПК.",
    "SSH private key was not found.": "Приватный ключ SSH не найден.",
    "Connect and render": "Подключиться и рендерить",
    "Use this PC": "Использовать этот ПК",
    "Disconnect": "Отключиться",
    "Disconnect selected device": "Отключить выбранное устройство",
    "Its active frame returns to the queue": "Активный кадр вернётся в очередь",
    "Disconnect device": "Отключить устройство",
    "Start the main computer controller first.": "Сначала запустите контроллер на главном компьютере.",
    "Select a connected device first.": "Сначала выберите подключённое устройство.",
    "The main computer cannot disconnect itself.": "Главный компьютер не может отключить сам себя.",
    "This device is no longer connected.": "Это устройство больше не подключено.",
    "Disconnect {device} from this render network? Its active frame will return to the queue.": "Отключить {device} от этой сети рендера? Активный кадр вернётся в очередь.",
    "Disconnected {device}": "Устройство {device} отключено",
    "Device was already disconnected": "Устройство уже было отключено",
    "Connected devices": "Подключённые устройства",
    "Select a device to open its render settings": "Выберите устройство, чтобы открыть настройки рендера",
    "Device settings": "Настройки устройства",
    "Connected device render controls": "Параметры рендера подключённого устройства",
    "Render hardware": "Оборудование рендера",
    "Render device": "Устройство рендера",
    "Current frame": "Текущий кадр",
    "Completed frames": "Готовые кадры",
    "Average frame time": "Среднее время кадра",
    "Frame allocation": "Диапазон кадров",
    "Apply settings": "Применить настройки",
    "Automatic balancing": "Автоматическая балансировка",
    "Disconnect from main PC": "Отключить от главного ПК",
    "Device": "Устройство",
    "Hardware": "Оборудование",
    "Frame": "Кадр",
    "Done": "Готово",
    "Avg": "Среднее",
    "Allocation": "Диапазон",
    "Manual allocation": "Ручное распределение",
    "from": "от",
    "to": "до",
    "Apply": "Применить",
    "Leave empty for automatic balancing": "Оставьте пустым для автобалансировки",
    "Render prediction": "Прогноз рендера",
    "Uses project history when available and a scene heuristic otherwise.": "Использует историю проекта или оценку параметров сцены.",
    "Analyze scene": "Анализировать сцену",
    "Auto Fix": "Автоисправление",
    "Checks output, frame range, GPU, disk space, external files and FFmpeg.": "Проверяет вывод, диапазон кадров, GPU, место на диске, внешние файлы и FFmpeg.",
    "Run preflight": "Запустить проверку",
    "Apply safe fixes": "Исправить безопасно",
    "Render history": "История рендера",
    "Result": "Результат",
    "Time": "Время",
    "Rendered": "Отрендерено",
    "Hardest frames": "Самые тяжёлые кадры",
    "Render time": "Время рендера",
    "Render Sandbox": "Песочница рендера",
    "Test one frame with Draft, Balanced and Quality settings, then compare speed and quality proxy.": "Тестирует один кадр в режимах Черновик, Баланс и Качество, затем сравнивает скорость и качество.",
    "Test frame": "Тестовый кадр",
    "Run variants in parallel": "Запускать варианты параллельно",
    "Parallel mode is faster but can exhaust GPU memory.": "Параллельный режим быстрее, но может исчерпать память GPU.",
    "Run comparison": "Запустить сравнение",
    "Comparison results": "Результаты сравнения",
    "Variant": "Вариант",
    "Samples": "Сэмплы",
    "Resolution": "Разрешение",
    "Quality": "Качество",
    "Render Settings": "Настройки рендера",
    "Frame range": "Диапазон кадров",
    "Use .blend range": "Диапазон из .blend",
    "Crash retries": "Повторы после сбоя",
    "Output mode": "Режим вывода",
    "Compose frames after render": "Собрать видео после рендера",
    "Format": "Формат",
    "Optimization": "Оптимизация",
    "Marked options are applied before render starts. Some trade quality for speed.": "Отмеченные параметры применяются перед рендером. Некоторые ускоряют работу ценой качества.",
    "Auto optimize": "Автооптимизация",
    "Apply optimization before render": "Применять оптимизацию перед рендером",
    "Adaptive sampling": "Адаптивный сэмплинг",
    "Adaptive Sampling": "Адаптивный сэмплинг",
    "Stop clean areas early": "Раньше завершать чистые области",
    "Denoise": "Шумоподавление",
    "Reduce samples while keeping the image clean": "Снижает число сэмплов, сохраняя чистое изображение",
    "Persistent data": "Постоянные данные",
    "Persistent Data": "Постоянные данные",
    "Reuse data between animation frames": "Повторно использует данные между кадрами анимации",
    "Fast bounces": "Быстрые отражения",
    "Limit Light Bounces": "Ограничить отражения света",
    "Lower bounce limits for faster Cycles renders": "Уменьшает число отражений для ускорения Cycles",
    "Simplify": "Упрощение",
    "Simplify Geometry": "Упростить геометрию",
    "Reduce subdivision and texture limits": "Снижает уровни подразделения и ограничения текстур",
    "Tile size": "Размер тайла",
    "Auto preset": "Автопредустановка",
    "Auto enables the safest speed wins: GPU, adaptive sampling, denoise, persistent data, limited bounces, samples 256, tile 256, full resolution. Simplify stays off because it can visibly change geometry.": "Авто включает безопасные ускорения: GPU, адаптивный сэмплинг, шумоподавление, постоянные данные, ограниченные отражения, 256 сэмплов и тайл 256. Упрощение остаётся выключенным, поскольку может заметно изменить геометрию.",
    "Speed checklist": "Что ускоряет рендер",
    "⚡ Strong speedup: GPU, fewer samples, denoise, adaptive sampling.\n\n⚡ Animation speedup: persistent data.\n\n⚠ Quality tradeoff: bounces, simplify, resolution percent.": "⚡ Сильное ускорение: GPU, меньше сэмплов, шумоподавление, адаптивный сэмплинг.\n\n⚡ Ускорение анимации: постоянные данные.\n\n⚠ Компромисс качества: отражения, упрощение, процент разрешения.",
    "GitHub Updates": "Обновления GitHub",
    "No paste needed: default source is github:prostoodin1/BlenderRenderWatchdog. Advanced users can override it here.": "Ничего вставлять не нужно: источник по умолчанию — github:prostoodin1/BlenderRenderWatchdog. Опытные пользователи могут изменить его здесь.",
    "Update source": "Источник обновлений",
    "Check updates on start": "Проверять при запуске",
    "Install updates automatically": "Устанавливать автоматически",
    "Check update": "Проверить обновление",
    "Install update": "Установить обновление",
    "Publish to GitHub": "Опубликовать на GitHub",
    "Power": "Питание",
    "Optional actions after a successful render. Shutdown starts with a 60 second Windows countdown.": "Действия после успешного рендера. Выключение Windows начнётся с отсчёта в 60 секунд.",
    "Shutdown PC after successful render": "Выключить ПК после рендера",
    "Tip: if shutdown starts accidentally, run `shutdown /a` in Windows to cancel it.": "Совет: если выключение запущено случайно, выполните `shutdown /a` в Windows для отмены.",
    "Interface": "Интерфейс",
    "Language": "Язык",
    "Changes apply instantly and the selected language is remembered.": "Изменения применяются сразу, выбранный язык сохраняется.",
    "Colour theme": "Цветовая тема",
    "Choose custom colour": "Выбрать свой цвет",
    "Choose interface colour": "Выберите цвет интерфейса",
    "Lightweight transitions": "Облегчённые переходы",
    "Fast transitions": "Быстрые переходы",
    "Graphite": "Графит",
    "Ocean": "Океан",
    "Emerald": "Изумруд",
    "Amber": "Янтарь",
    "Rose": "Роза",
    "Violet": "Фиолетовый",
    "Custom": "Свой цвет",
    "Mobile dashboard": "Мобильная панель",
    "Open the private LAN link on a phone to view progress, previews and control the render.": "Откройте приватную ссылку локальной сети на телефоне для просмотра прогресса, превью и управления рендером.",
    "Android sync code": "Код синхронизации Android",
    "Copy sync code": "Копировать код синхронизации",
    "Start the mobile service to create a sync code": "Запустите мобильный сервис, чтобы создать код синхронизации",
    "Start with the app": "Запускать вместе с приложением",
    "Start": "Запустить",
    "Copy link": "Копировать ссылку",
    "LAN security": "Безопасность локальной сети",
    "Network and mobile links use random access tokens. Share them only with devices on networks you trust.": "Сетевые и мобильные ссылки используют случайные токены доступа. Передавайте их только доверенным устройствам.",
    "Choose fresh codes for every start or keep your own key for stable LAN access.": "Создавайте новые коды при каждом запуске или сохраните свой ключ для постоянного доступа в локальной сети.",
    "Code behaviour": "Поведение кодов",
    "Saved access key": "Сохранённый ключ доступа",
    "New every start": "Новые при каждом запуске",
    "Keep on this network": "Постоянные в этой сети",
    "Generate every start": "Генерировать при каждом запуске",
    "Keep my code": "Сохранить мой код",
    "Your access key": "Ваш ключ доступа",
    "Apply access": "Применить доступ",
    "New key": "Новый ключ",
    "Startup recovery": "Восстановление при запуске",
    "If Windows restarts before a render finishes, create a temporary Startup file and continue at the next login.": "Если Windows перезапустится до конца рендера, приложение создаст временный файл автозапуска и продолжит работу при следующем входе.",
    "Resume unfinished render at Windows login": "Продолжать незаконченный рендер при входе в Windows",
    "Resume after restart": "Автопродолжение после перезапуска",
    "Startup recovery is off": "Восстановление при запуске выключено",
    "Ready · a Startup file will be created when rendering begins": "Готово · файл автозапуска будет создан в начале рендера",
    "Automatic recovery paused after 3 attempts": "Автовосстановление приостановлено после 3 попыток",
    "Recovery armed · attempt {attempt}/3": "Восстановление активно · попытка {attempt}/3",
    "Recovery paused": "Восстановление приостановлено",
    "Open the app and start the render manually": "Откройте приложение и запустите рендер вручную",
    "Ready": "Готово",
    "Waiting for render setup": "Ожидание настройки рендера",
    "Mobile dashboard is stopped": "Мобильная панель остановлена",
    "Select a project and run Analyze": "Выберите проект и запустите анализ",
    "Memory: —": "Память: —",
    "Preflight has not been run": "Предварительная проверка не запускалась",
    "Controller is stopped": "Контроллер остановлен",
    "Render worker": "Исполнитель рендера",
    "Ready to compare Draft, Balanced and Quality": "Готово к сравнению Черновика, Баланса и Качества",
    "Current version: {version}": "Текущая версия: {version}",
    "Queue is empty": "Очередь пуста",
    "{total} projects · {pending} waiting": "Проектов: {total} · ожидают: {pending}",
    "Analyzing queued projects…": "Анализ проектов в очереди…",
    "Checking for updates...": "Проверка обновлений...",
    "Already latest: {version}": "Уже установлена последняя версия: {version}",
    "Update available: {version}": "Доступно обновление: {version}",
    "Applied {count} safe fix(es). Re-run preflight to verify.": "Применено безопасных исправлений: {count}. Запустите проверку ещё раз.",
    "Analyzing scene…": "Анализ сцены…",
    "Running preflight…": "Выполняется проверка…",
    "Running sandbox variants…": "Запуск вариантов песочницы…",
    "Controller ready · 0/{maximum} devices": "Контроллер готов · 0/{maximum} устройств",
    "Approx. remaining time appears after the first frame": "Примерное оставшееся время появится после первого кадра",
    "Approx. remaining: {time}": "Примерно осталось: {time}",
    "Measuring network render speed…": "Измерение скорости сетевого рендера…",
    "Render complete": "Рендер завершён",
    "Connection code copied": "Код подключения скопирован",
    "Network setup": "Настройка сети",
    "Packing project assets for workers": "Упаковка ресурсов проекта для исполнителей",
    "Preparing a packed project copy…": "Подготовка упакованной копии проекта…",
    "Sharing the selected project with workers": "Передача выбранного проекта исполнителям",
    "Preparing the original project…": "Подготовка исходного проекта…",
    "Controller active · {online}/{maximum} devices": "Контроллер активен · {online}/{maximum} устройств",
    "Controller ready via {connection} · 0/{maximum} devices": "Контроллер готов через {connection} · 0/{maximum} устройств",
    "Waiting for network render": "Ожидание сетевого рендера",
    "No ETA yet": "Оценки времени пока нет",
    "Network frames {completed}/{total} · {progress}%": "Сетевые кадры {completed}/{total} · {progress}%",
    "About {time} left": "Осталось около {time}",
    "Measuring speed…": "Измерение скорости…",
    "Frames {start}-{end} · {completed}/{total} · {per_minute}/min · {per_hour}/hour": "Кадры {start}-{end} · {completed}/{total} · {per_minute}/мин · {per_hour}/ч",
    "{completed} / {total} network frames": "{completed} / {total} сетевых кадров",
    "Network complete": "Сетевой рендер завершён",
    "{completed} complete · {failed} failed": "Готово: {completed} · ошибок: {failed}",
    "Could not start: {error}": "Не удалось запустить: {error}",
    "Starting": "Запуск",
    "Running": "Выполняется",
    "Blender process is active": "Процесс Blender активен",
    "Queue starting": "Запуск очереди",
    "Preparing the first project": "Подготовка первого проекта",
    "Pausing": "Приостановка",
    "Waiting for current frame to finish": "Ожидание завершения текущего кадра",
    "Stopping": "Остановка",
    "Terminating Blender safely": "Безопасное завершение Blender",
    "No common problems found. Ready to render.": "Типовых проблем не найдено. Можно запускать рендер.",
    "≈ {total} total · {per_frame}/frame": "≈ {total} всего · {per_frame}/кадр",
    "Memory ≈ {memory:.1f} GB · {confidence} confidence · {source} · difficult frames: {frames}": "Память ≈ {memory:.1f} ГБ · уверенность: {confidence} · источник: {source} · сложные кадры: {frames}",
    "Sandbox failed: {error}": "Ошибка песочницы: {error}",
    "Recommended: {variant} · {duration} · quality {quality}%": "Рекомендуется: {variant} · {duration} · качество {quality}%",
    "No sandbox variant completed successfully": "Ни один вариант песочницы не завершился успешно",
    "Network render": "Сетевой рендер",
    "Distributing frames {start}-{end}": "Распределение кадров {start}–{end}",
    "Distributed render is running": "Сетевой рендер выполняется",
    "Network error": "Ошибка сети",
    "Rendering {project}": "Рендер проекта {project}",
    "Paused": "Пауза",
    "Queue can continue from the next frame": "Очередь можно продолжить со следующего кадра",
    "Continue queue": "Продолжить очередь",
    "Stopped": "Остановлено",
    "Render queue stopped": "Очередь рендера остановлена",
    "Queue complete": "Очередь завершена",
    "Complete": "Завершено",
    "Render finished normally": "Рендер завершён успешно",
    "Ready to resume from the next frame": "Можно продолжить со следующего кадра",
    "Resume Render": "Продолжить рендер",
    "Render stopped by user": "Рендер остановлен пользователем",
    "Error": "Ошибка",
    "Process exited with code {code}": "Процесс завершился с кодом {code}",
    "Blend file not found": "Файл Blender не найден",
    "Choose an existing .blend file first.": "Сначала выберите существующий файл .blend.",
    "Frames folder missing": "Папка кадров не указана",
    "Choose an output folder or enable the .blend output path.": "Выберите папку вывода или включите путь из .blend.",
    "Publisher missing": "Средство публикации не найдено",
    "Publish To GitHub.cmd was not found near the app.": "Файл Publish To GitHub.cmd не найден рядом с приложением.",
    "Publisher failed": "Ошибка публикации",
    "No update": "Нет данных об обновлении",
    "Check updates first.": "Сначала проверьте обновления.",
    "Install update?": "Установить обновление?",
    "The app will close, download the new version and restart. Install update?": "Приложение закроется, загрузит новую версию и перезапустится. Установить обновление?",
    "Update failed": "Ошибка обновления",
    "Invalid frame range": "Неверный диапазон кадров",
    "Start frame": "Начальный кадр",
    "End frame": "Конечный кадр",
    "{field} must be a number.": "Поле «{field}» должно быть числом.",
    "{field} cannot be less than 0.": "Поле «{field}» не может быть меньше 0.",
    "Start frame cannot be greater than End frame.": "Начальный кадр не может быть больше конечного.",
    "Scene output not found": "Путь вывода сцены не найден",
    "Could not read the output path from the .blend file.": "Не удалось прочитать путь сохранения из файла .blend.",
    "Choose a frames folder or enable Use .blend output path.": "Выберите папку кадров или включите путь вывода из .blend.",
    "Render device missing": "Не выбрано устройство рендера",
    "Blender not found": "Blender не найден",
    "blender.exe was not found. Choose it manually.": "blender.exe не найден. Выберите его вручную.",
    "Blend file not found": "Файл .blend не найден",
    "The .blend file was not found.": "Файл .blend не найден.",
    "Project missing": "Проект не указан",
    "Choose an existing Blender executable and .blend project first.": "Сначала выберите существующие blender.exe и проект .blend.",
    "Invalid frame": "Неверный номер кадра",
    "Sandbox frame must be a number.": "Номер кадра песочницы должен быть числом.",
    "Network controller": "Сетевой контроллер",
    "Worker setup": "Настройка исполнителя",
    "Enter a connection code and choose blender.exe.": "Введите код подключения и выберите blender.exe.",
    "Join render network": "Подключиться к сети рендера",
    "This computer will download the project and render assigned frames. Ready to connect?": "Этот компьютер загрузит проект и отрендерит назначенные кадры. Подключиться?",
    "Worker connection": "Подключение исполнителя",
    "Allocation": "Распределение",
    "Choose blender.exe on the Render tab first.": "Сначала выберите blender.exe на вкладке «Рендер».",
    "Choose at least CPU or GPU for rendering.": "Выберите хотя бы CPU или GPU для рендера.",
    "Queue complete": "Очередь завершена",
    "There are no waiting projects in the queue.": "В очереди нет ожидающих проектов.",
    "Stop render": "Остановить рендер",
    "Render is running. Stop Blender and close the window?": "Рендер запущен. Остановить Blender и закрыть окно?",
    "ACTIVE PROJECT": "АКТИВНЫЙ ПРОЕКТ",
    "Active project": "Активный проект",
    "Assignment": "Пакет кадров",
    "Automatic hardware selection with editable frame chunks": "Автоматический выбор оборудования и настраиваемые пакеты кадров",
    "Blender output and recovery events": "Вывод Blender и события восстановления",
    "Close": "Закрыть",
    "Code only for protected groups": "Код нужен только для защищённых групп",
    "Connect by invitation": "Подключиться по приглашению",
    "Connection": "Подключение",
    "Advanced": "Дополнительно",
    "Copy invite": "Копировать приглашение",
    "Cycles": "Cycles",
    "Cycles backend": "Система Cycles",
    "Devices": "Устройства",
    "Failover": "Смена главного ПК",
    "Frames per assignment": "Кадров в задании",
    "Join group": "Войти в группу",
    "LAN is always available. SSH is used as the saved route between different networks.": "Локальная сеть доступна всегда. SSH используется как сохранённый маршрут между разными сетями.",
    "Main PC": "Главный ПК",
    "Worker": "Рабочий ПК",
    "Available groups": "Доступные группы",
    "Group": "Группа",
    "Generate SSH key": "Сгенерировать SSH-ключ",
    "Create ready SSH link": "Создать готовую SSH-ссылку",
    "SSH invitation link": "Ссылка-приглашение SSH",
    "BRW code or one-time LAN code": "Код BRW или одноразовый код LAN",
    "Paste an SSH invitation in the SSH field or use the BRW field below.": "Вставьте SSH-приглашение в поле SSH или используйте поле BRW ниже.",
    "Remembered": "Сохранена",
    "No available or remembered groups were found.": "Доступные или сохранённые группы не найдены.",
    "This group is currently offline.": "Эта группа сейчас не в сети.",
    "One queue, one active project": "Одна очередь и один активный проект",
    "Pause": "Пауза",
    "Projects": "Проекты",
    "Render group": "Группа рендера",
    "Render on group": "Рендерить на группе",
    "Render queue": "Запустить очередь",
    "Render strategy": "Стратегия рендера",
    "SSH key": "SSH-ключ",
    "Save": "Сохранить",
    "Saved invitation": "Сохранённое приглашение",
    "Select to configure": "Выберите для настройки",
    "Start group": "Запустить группу",
    "Transport": "Способ подключения",
    "Use project output": "Использовать путь проекта",
    "Visible on LAN": "Показывать в локальной сети",
    "Project output": "Путь из проекта",
    "No active project": "Нет активного проекта",
    "Average": "Среднее",
    "Workspace": "Рабочий экран",
    "Open group": "Открытая группа",
    "Approval required": "Нужно подтверждение",
    "Auto main": "Автовыбор главного",
    "Automatic hardware and frame chunks": "Автовыбор оборудования и пакетов кадров",
    "Connection settings": "Настройки подключения",
    "New group": "Новая группа",
    "Group name": "Название группы",
    "Stop the current group before creating another one.": "Остановите текущую группу перед созданием новой.",
    "Group created. Start it to accept devices.": "Группа создана. Запустите её для подключения устройств.",
    "Disconnect before switching render groups.": "Отключитесь перед переключением группы рендера.",
    "Selected group: {group}": "Выбрана группа: {group}",
    "Invitation from this main PC": "Приглашение с этого главного ПК",
    "Creates a dedicated SSH key and copies a trusted invitation link. Share it only with your render devices.": "Создаёт отдельный SSH-ключ и копирует доверенную ссылку-приглашение. Передавайте её только своим устройствам рендера.",
    "Create and copy SSH invite": "Создать и скопировать SSH-приглашение",
    "Invitation received on this PC": "Приглашение, полученное на этом ПК",
    "SSH invitation": "SSH-приглашение",
    "Switch this device to Main PC before creating an invitation.": "Перед созданием приглашения переключите это устройство в режим главного ПК.",
    "Creating SSH key and configuring the main PC…": "Создание SSH-ключа и настройка главного ПК…",
    "SSH invitation is ready and copied": "SSH-приглашение готово и скопировано",
    "SSH invitation copied; start the group and share it with trusted devices": "SSH-приглашение скопировано; запустите группу и передайте ссылку доверенным устройствам",
    "The SSH invitation was copied. It contains a private access key, so share it only with devices you trust.": "SSH-приглашение скопировано. Оно содержит приватный ключ доступа, поэтому передавайте его только доверенным устройствам.",
    "SSH invitation could not be created": "Не удалось создать SSH-приглашение",
}


TRANSLATIONS = {"ru": RUSSIAN_TRANSLATIONS}


def detect_default_language() -> str:
    """Select Russian on Russian systems and English everywhere else."""
    try:
        current = locale.getlocale()[0] or ""
    except (ValueError, TypeError):
        current = ""
    return "ru" if current.lower().startswith("ru") else "en"


def normalize_language(value: str | None) -> str:
    candidate = str(value or "").strip().lower()
    for code, label in LANGUAGE_LABELS.items():
        if candidate in {code, label.lower()}:
            return code
    return detect_default_language()


def language_code_from_label(label: str) -> str:
    return normalize_language(label)


def translate(source: str, language: str, **values: object) -> str:
    template = TRANSLATIONS.get(normalize_language(language), {}).get(source, source)
    try:
        return template.format(**values)
    except (KeyError, ValueError):
        return template
