"""Small, dependency-free localization layer for the desktop interface."""

from __future__ import annotations

import locale


LANGUAGE_LABELS = {
    "en": "English",
    "ru": "Русский",
}


RUSSIAN_TRANSLATIONS = {
    "Smart recovery, distributed rendering, prediction and phone control.": "Умное восстановление, сетевой рендер, прогнозирование и управление с телефона.",
    "Smart queue": "Умная очередь",
    "Network ×5": "Сеть ×5",
    "Mobile control": "Мобильное управление",
    "History + Auto Fix": "История + автоисправление",
    "CURRENT STATE": "ТЕКУЩЕЕ СОСТОЯНИЕ",
    "Render": "Рендер",
    "Queue": "Очередь",
    "Network": "Сеть",
    "Insights": "Аналитика",
    "Sandbox": "Песочница",
    "Advanced": "Расширенные",
    "Settings": "Настройки",
    "Logs": "Журнал",
    "Project Setup": "Настройка проекта",
    "Scene file, output frames folder, and detected Blender runtime.": "Файл сцены, папка кадров и найденная версия Blender.",
    "Blender": "Blender",
    ".blend file": "Файл .blend",
    "Frames folder": "Папка кадров",
    "Browse": "Обзор",
    "Use .blend output path": "Использовать путь из .blend",
    "Render Device": "Устройство рендера",
    "Pick render devices. Cycles preferences are applied at launch.": "Выберите устройства. Настройки Cycles применяются при запуске.",
    "Use GPU": "Использовать GPU",
    "Use CPU": "Использовать CPU",
    "Render Timeline": "Ход рендера",
    "Start render": "Начать рендер",
    "Pause after frame": "Пауза после кадра",
    "Stop now": "Остановить",
    "Pause waits for the current frame, Stop terminates Blender now.": "Пауза дождётся текущего кадра, остановка завершит Blender сразу.",
    "Live Console": "Консоль",
    "Terminal stream, crashes, restarts and completed frames": "Вывод Blender, сбои, перезапуски и готовые кадры",
    "Render Queue": "Очередь рендера",
    "Estimate projects, put shorter work first, retry failures and continue automatically.": "Оценивает проекты, ставит короткие первыми, повторяет сбои и продолжает автоматически.",
    "Add current": "Добавить текущий",
    "Add files": "Добавить файлы",
    "Remove": "Удалить",
    "Estimate + sort": "Оценить и упорядочить",
    "Project": "Проект",
    "Frames": "Кадры",
    "Mode": "Режим",
    "Estimate": "Оценка",
    "Output": "Результат",
    "Status": "Статус",
    "Shortest projects first": "Сначала короткие проекты",
    "Start queue": "Запустить очередь",
    "Controller": "Контроллер",
    "Choose this device's role": "Выберите роль этого устройства",
    "Connect to another computer or make this computer the main render controller.": "Подключитесь к другому компьютеру или сделайте этот компьютер главным для рендера.",
    "Connect": "Подключиться",
    "Become main": "Стать главным",
    "Main computer": "Главный компьютер",
    "Connect to main computer": "Подключиться к главному компьютеру",
    "Use this computer for rendering": "Использовать этот компьютер для рендера",
    "Main": "Главный",
    "Online": "В сети",
    "Offline": "Не в сети",
    "Auto": "Авто",
    "Connected to {controller} · {online} devices": "Подключено к {controller} · устройств в сети: {online}",
    "Create a LAN code and distribute individual frames to up to five PCs.": "Создайте код локальной сети и распределяйте кадры между пятью ПК.",
    "Start controller": "Запустить контроллер",
    "Copy code": "Копировать код",
    "Stop": "Остановить",
    "Start distributed render": "Запустить сетевой рендер",
    "Worker mode": "Режим исполнителя",
    "Enter the code on another computer. The project is downloaded automatically.": "Введите код на другом компьютере. Проект загрузится автоматически.",
    "This PC name": "Имя этого ПК",
    "Connection code": "Код подключения",
    "Connect and render": "Подключиться и рендерить",
    "Use this PC": "Использовать этот ПК",
    "Disconnect": "Отключиться",
    "Connected devices": "Подключённые устройства",
    "Device": "Устройство",
    "Hardware": "Оборудование",
    "Frame": "Кадр",
    "Done": "Готово",
    "Avg": "Среднее",
    "Allocation": "Диапазон",
    "Manual allocation": "Ручное распределение",
    "from": "от",
    "to": "до",
    "Apply": "Применить",
    "Leave empty for automatic balancing": "Оставьте пустым для автобалансировки",
    "Render prediction": "Прогноз рендера",
    "Uses project history when available and a scene heuristic otherwise.": "Использует историю проекта или оценку параметров сцены.",
    "Analyze scene": "Анализировать сцену",
    "Auto Fix": "Автоисправление",
    "Checks output, frame range, GPU, disk space, external files and FFmpeg.": "Проверяет вывод, диапазон кадров, GPU, место на диске, внешние файлы и FFmpeg.",
    "Run preflight": "Запустить проверку",
    "Apply safe fixes": "Исправить безопасно",
    "Render history": "История рендера",
    "Result": "Результат",
    "Time": "Время",
    "Rendered": "Отрендерено",
    "Hardest frames": "Самые тяжёлые кадры",
    "Render time": "Время рендера",
    "Render Sandbox": "Песочница рендера",
    "Test one frame with Draft, Balanced and Quality settings, then compare speed and quality proxy.": "Тестирует один кадр в режимах Черновик, Баланс и Качество, затем сравнивает скорость и качество.",
    "Test frame": "Тестовый кадр",
    "Run variants in parallel": "Запускать варианты параллельно",
    "Parallel mode is faster but can exhaust GPU memory.": "Параллельный режим быстрее, но может исчерпать память GPU.",
    "Run comparison": "Запустить сравнение",
    "Comparison results": "Результаты сравнения",
    "Variant": "Вариант",
    "Samples": "Сэмплы",
    "Resolution": "Разрешение",
    "Quality": "Качество",
    "Render Settings": "Настройки рендера",
    "Frame range": "Диапазон кадров",
    "Use .blend range": "Диапазон из .blend",
    "Crash retries": "Повторы после сбоя",
    "Output mode": "Режим вывода",
    "Compose frames after render": "Собрать видео после рендера",
    "Format": "Формат",
    "Optimization": "Оптимизация",
    "Marked options are applied before render starts. Some trade quality for speed.": "Отмеченные параметры применяются перед рендером. Некоторые ускоряют работу ценой качества.",
    "Auto optimize": "Автооптимизация",
    "Apply optimization before render": "Применять оптимизацию перед рендером",
    "Adaptive sampling": "Адаптивный сэмплинг",
    "Adaptive Sampling": "Адаптивный сэмплинг",
    "Stop clean areas early": "Раньше завершать чистые области",
    "Denoise": "Шумоподавление",
    "Reduce samples while keeping the image clean": "Снижает число сэмплов, сохраняя чистое изображение",
    "Persistent data": "Постоянные данные",
    "Persistent Data": "Постоянные данные",
    "Reuse data between animation frames": "Повторно использует данные между кадрами анимации",
    "Fast bounces": "Быстрые отражения",
    "Limit Light Bounces": "Ограничить отражения света",
    "Lower bounce limits for faster Cycles renders": "Уменьшает число отражений для ускорения Cycles",
    "Simplify": "Упрощение",
    "Simplify Geometry": "Упростить геометрию",
    "Reduce subdivision and texture limits": "Снижает уровни подразделения и ограничения текстур",
    "Tile size": "Размер тайла",
    "Auto preset": "Автопредустановка",
    "Auto enables the safest speed wins: GPU, adaptive sampling, denoise, persistent data, limited bounces, samples 256, tile 256, full resolution. Simplify stays off because it can visibly change geometry.": "Авто включает безопасные ускорения: GPU, адаптивный сэмплинг, шумоподавление, постоянные данные, ограниченные отражения, 256 сэмплов и тайл 256. Упрощение остаётся выключенным, поскольку может заметно изменить геометрию.",
    "Speed checklist": "Что ускоряет рендер",
    "⚡ Strong speedup: GPU, fewer samples, denoise, adaptive sampling.\n\n⚡ Animation speedup: persistent data.\n\n⚠ Quality tradeoff: bounces, simplify, resolution percent.": "⚡ Сильное ускорение: GPU, меньше сэмплов, шумоподавление, адаптивный сэмплинг.\n\n⚡ Ускорение анимации: постоянные данные.\n\n⚠ Компромисс качества: отражения, упрощение, процент разрешения.",
    "GitHub Updates": "Обновления GitHub",
    "No paste needed: default source is github:prostoodin1/BlenderRenderWatchdog. Advanced users can override it here.": "Ничего вставлять не нужно: источник по умолчанию — github:prostoodin1/BlenderRenderWatchdog. Опытные пользователи могут изменить его здесь.",
    "Update source": "Источник обновлений",
    "Check updates on start": "Проверять при запуске",
    "Install updates automatically": "Устанавливать автоматически",
    "Check update": "Проверить обновление",
    "Install update": "Установить обновление",
    "Publish to GitHub": "Опубликовать на GitHub",
    "Power": "Питание",
    "Optional actions after a successful render. Shutdown starts with a 60 second Windows countdown.": "Действия после успешного рендера. Выключение Windows начнётся с отсчёта в 60 секунд.",
    "Shutdown PC after successful render": "Выключить ПК после успешного рендера",
    "Tip: if shutdown starts accidentally, run `shutdown /a` in Windows to cancel it.": "Совет: если выключение запущено случайно, выполните `shutdown /a` в Windows для отмены.",
    "Interface": "Интерфейс",
    "Language": "Язык",
    "Changes apply instantly and the selected language is remembered.": "Изменения применяются сразу, выбранный язык сохраняется.",
    "Mobile dashboard": "Мобильная панель",
    "Open the private LAN link on a phone to view progress, previews and control the render.": "Откройте приватную ссылку локальной сети на телефоне для просмотра прогресса, превью и управления рендером.",
    "Start with the app": "Запускать вместе с приложением",
    "Start": "Запустить",
    "Copy link": "Копировать ссылку",
    "LAN security": "Безопасность локальной сети",
    "Network and mobile links use random access tokens. Share them only with devices on networks you trust.": "Сетевые и мобильные ссылки используют случайные токены доступа. Передавайте их только доверенным устройствам.",
    "Ready": "Готово",
    "Waiting for render setup": "Ожидание настройки рендера",
    "Mobile dashboard is stopped": "Мобильная панель остановлена",
    "Select a project and run Analyze": "Выберите проект и запустите анализ",
    "Memory: —": "Память: —",
    "Preflight has not been run": "Предварительная проверка не запускалась",
    "Controller is stopped": "Контроллер остановлен",
    "Render worker": "Исполнитель рендера",
    "Ready to compare Draft, Balanced and Quality": "Готово к сравнению Черновика, Баланса и Качества",
    "Current version: {version}": "Текущая версия: {version}",
    "Queue is empty": "Очередь пуста",
    "{total} projects · {pending} waiting": "Проектов: {total} · ожидают: {pending}",
    "Analyzing queued projects…": "Анализ проектов в очереди…",
    "Checking for updates...": "Проверка обновлений...",
    "Already latest: {version}": "Уже установлена последняя версия: {version}",
    "Update available: {version}": "Доступно обновление: {version}",
    "Applied {count} safe fix(es). Re-run preflight to verify.": "Применено безопасных исправлений: {count}. Запустите проверку ещё раз.",
    "Analyzing scene…": "Анализ сцены…",
    "Running preflight…": "Выполняется проверка…",
    "Running sandbox variants…": "Запуск вариантов песочницы…",
    "Controller ready · 0/{maximum} devices": "Контроллер готов · 0/{maximum} устройств",
    "Connection code copied": "Код подключения скопирован",
    "Network setup": "Настройка сети",
    "Packing project assets for workers": "Упаковка ресурсов проекта для исполнителей",
    "Preparing a packed project copy…": "Подготовка упакованной копии проекта…",
    "Controller active · {online}/{maximum} devices": "Контроллер активен · {online}/{maximum} устройств",
    "{completed} / {total} network frames": "{completed} / {total} сетевых кадров",
    "Network complete": "Сетевой рендер завершён",
    "{completed} complete · {failed} failed": "Готово: {completed} · ошибок: {failed}",
    "Could not start: {error}": "Не удалось запустить: {error}",
    "Starting": "Запуск",
    "Running": "Выполняется",
    "Blender process is active": "Процесс Blender активен",
    "Queue starting": "Запуск очереди",
    "Preparing the first project": "Подготовка первого проекта",
    "Pausing": "Приостановка",
    "Waiting for current frame to finish": "Ожидание завершения текущего кадра",
    "Stopping": "Остановка",
    "Terminating Blender safely": "Безопасное завершение Blender",
    "No common problems found. Ready to render.": "Типовых проблем не найдено. Можно запускать рендер.",
    "≈ {total} total · {per_frame}/frame": "≈ {total} всего · {per_frame}/кадр",
    "Memory ≈ {memory:.1f} GB · {confidence} confidence · {source} · difficult frames: {frames}": "Память ≈ {memory:.1f} ГБ · уверенность: {confidence} · источник: {source} · сложные кадры: {frames}",
    "Sandbox failed: {error}": "Ошибка песочницы: {error}",
    "Recommended: {variant} · {duration} · quality {quality}%": "Рекомендуется: {variant} · {duration} · качество {quality}%",
    "No sandbox variant completed successfully": "Ни один вариант песочницы не завершился успешно",
    "Network render": "Сетевой рендер",
    "Distributing frames {start}-{end}": "Распределение кадров {start}–{end}",
    "Distributed render is running": "Сетевой рендер выполняется",
    "Network error": "Ошибка сети",
    "Rendering {project}": "Рендер проекта {project}",
    "Paused": "Пауза",
    "Queue can continue from the next frame": "Очередь можно продолжить со следующего кадра",
    "Continue queue": "Продолжить очередь",
    "Stopped": "Остановлено",
    "Render queue stopped": "Очередь рендера остановлена",
    "Queue complete": "Очередь завершена",
    "Complete": "Завершено",
    "Render finished normally": "Рендер завершён успешно",
    "Ready to resume from the next frame": "Можно продолжить со следующего кадра",
    "Resume Render": "Продолжить рендер",
    "Render stopped by user": "Рендер остановлен пользователем",
    "Error": "Ошибка",
    "Process exited with code {code}": "Процесс завершился с кодом {code}",
    "Blend file not found": "Файл Blender не найден",
    "Choose an existing .blend file first.": "Сначала выберите существующий файл .blend.",
    "Frames folder missing": "Папка кадров не указана",
    "Choose an output folder or enable the .blend output path.": "Выберите папку вывода или включите путь из .blend.",
    "Publisher missing": "Средство публикации не найдено",
    "Publish To GitHub.cmd was not found near the app.": "Файл Publish To GitHub.cmd не найден рядом с приложением.",
    "Publisher failed": "Ошибка публикации",
    "No update": "Нет данных об обновлении",
    "Check updates first.": "Сначала проверьте обновления.",
    "Install update?": "Установить обновление?",
    "The app will close, download the new version and restart. Install update?": "Приложение закроется, загрузит новую версию и перезапустится. Установить обновление?",
    "Update failed": "Ошибка обновления",
    "Invalid frame range": "Неверный диапазон кадров",
    "Start frame": "Начальный кадр",
    "End frame": "Конечный кадр",
    "{field} must be a number.": "Поле «{field}» должно быть числом.",
    "{field} cannot be less than 0.": "Поле «{field}» не может быть меньше 0.",
    "Start frame cannot be greater than End frame.": "Начальный кадр не может быть больше конечного.",
    "Scene output not found": "Путь вывода сцены не найден",
    "Could not read the output path from the .blend file.": "Не удалось прочитать путь сохранения из файла .blend.",
    "Choose a frames folder or enable Use .blend output path.": "Выберите папку кадров или включите путь вывода из .blend.",
    "Render device missing": "Не выбрано устройство рендера",
    "Blender not found": "Blender не найден",
    "blender.exe was not found. Choose it manually.": "blender.exe не найден. Выберите его вручную.",
    "Blend file not found": "Файл .blend не найден",
    "The .blend file was not found.": "Файл .blend не найден.",
    "Project missing": "Проект не указан",
    "Choose an existing Blender executable and .blend project first.": "Сначала выберите существующие blender.exe и проект .blend.",
    "Invalid frame": "Неверный номер кадра",
    "Sandbox frame must be a number.": "Номер кадра песочницы должен быть числом.",
    "Network controller": "Сетевой контроллер",
    "Worker setup": "Настройка исполнителя",
    "Enter a connection code and choose blender.exe.": "Введите код подключения и выберите blender.exe.",
    "Join render network": "Подключиться к сети рендера",
    "This computer will download the project and render assigned frames. Ready to connect?": "Этот компьютер загрузит проект и отрендерит назначенные кадры. Подключиться?",
    "Worker connection": "Подключение исполнителя",
    "Allocation": "Распределение",
    "Choose blender.exe on the Render tab first.": "Сначала выберите blender.exe на вкладке «Рендер».",
    "Choose at least CPU or GPU for rendering.": "Выберите хотя бы CPU или GPU для рендера.",
    "Queue complete": "Очередь завершена",
    "There are no waiting projects in the queue.": "В очереди нет ожидающих проектов.",
    "Stop render": "Остановить рендер",
    "Render is running. Stop Blender and close the window?": "Рендер запущен. Остановить Blender и закрыть окно?",
}


TRANSLATIONS = {"ru": RUSSIAN_TRANSLATIONS}


def detect_default_language() -> str:
    """Select Russian on Russian systems and English everywhere else."""
    try:
        current = locale.getlocale()[0] or ""
    except (ValueError, TypeError):
        current = ""
    return "ru" if current.lower().startswith("ru") else "en"


def normalize_language(value: str | None) -> str:
    candidate = str(value or "").strip().lower()
    for code, label in LANGUAGE_LABELS.items():
        if candidate in {code, label.lower()}:
            return code
    return detect_default_language()


def language_code_from_label(label: str) -> str:
    return normalize_language(label)


def translate(source: str, language: str, **values: object) -> str:
    template = TRANSLATIONS.get(normalize_language(language), {}).get(source, source)
    try:
        return template.format(**values)
    except (KeyError, ValueError):
        return template
